---
services:
  etcd-node-0:
    image: gcr.io/etcd-development/etcd:v3.5.21
    container_name: etcd-node-0
    restart: always
    environment:
      - ETCD_NAME=etcd-node-0
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node-0:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node-0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=etcd-node-0=http://etcd-node-0:2380,etcd-node-1=http://etcd-node-1:2380,etcd-node-2=http://etcd-node-2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=${ETCD_CLUSTER_TOKEN}
      - ETCD_DATA_DIR=/etcd-data
    volumes:
      - ./etcd-data-0:/etcd-data
    networks:
      - pg-cl-net
    expose:
      - "2379"
      - "2380"

  etcd-node-1:
    image: gcr.io/etcd-development/etcd:v3.5.21
    container_name: etcd-node-1
    restart: always
    environment:
      - ETCD_NAME=etcd-node-1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node-1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node-1:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=etcd-node-0=http://etcd-node-0:2380,etcd-node-1=http://etcd-node-1:2380,etcd-node-2=http://etcd-node-2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=${ETCD_CLUSTER_TOKEN}
      - ETCD_DATA_DIR=/etcd-data
    volumes:
      - ./etcd-data-1:/etcd-data
    networks:
      - pg-cl-net
    expose:
      - "2379"
      - "2380"

  etcd-node-2:
    image: gcr.io/etcd-development/etcd:v3.5.21
    container_name: etcd-node-2
    restart: always
    environment:
      - ETCD_NAME=etcd-node-2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node-2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node-2:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=etcd-node-0=http://etcd-node-0:2380,etcd-node-1=http://etcd-node-1:2380,etcd-node-2=http://etcd-node-2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=${ETCD_CLUSTER_TOKEN}
      - ETCD_DATA_DIR=/etcd-data
    volumes:
      - ./etcd-data-2:/etcd-data
    networks:
      - pg-cl-net
    expose:
      - "2379"
      - "2380"

  db-0:
    build:
      context: .
      dockerfile: Dockerfile
    image: patroni-postgres:17.5
    container_name: db-0
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - ./postgres-data-0:/var/lib/postgresql/data
      - ./patroni-config/config-0.yml:/etc/patroni/config.yml
    networks:
      - pg-cl-net
    depends_on:
      - etcd-node-0
      - etcd-node-1
      - etcd-node-2

  db-1:
    image: patroni-postgres:17.5
    container_name: db-1
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - ./postgres-data-1:/var/lib/postgresql/data
      - ./patroni-config/config-1.yml:/etc/patroni/config.yml
    networks:
      - pg-cl-net
    depends_on:
      - etcd-node-0
      - etcd-node-1
      - etcd-node-2


  db-2:
    image: patroni-postgres:17.5
    container_name: db-2
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - ./postgres-data-2:/var/lib/postgresql/data
      - ./patroni-config/config-2.yml:/etc/patroni/config.yml
    networks:
      - pg-cl-net
    depends_on:
      - etcd-node-0
      - etcd-node-1
      - etcd-node-2

networks:
  pg-cl-net:
    driver: bridge

